name: Backend CI Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: "appnumber3"  # Apne backend folder ka exact path yahan check kar lena

      - name: Build and Check Code Quality
        run: dotnet build --no-restore
        working-directory: "appnumber3"  # Apne backend folder ka exact path yahan check kar lena
